#!/bin/sh

CAT=/bin/cat

start() {
	echo "Turn up the lights in here, baby!"
	echo 100 > /sys/class/leds/lcd-backlight/brightness
	#cat /SDE-1024x768 > /dev/fb0
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
